version: 0.0
os: linux
files:
   - source: /index.html
     destination: /var/www/html/
     permission: sudo

hooks:
 BeforeInstall:
   - location: scripts/install.sh
     runas: root
 AfterInstall:
   - location: scripts/start.sh
     runas: root
